from generator import *
from pMetricGeneral3 import *
from scenarioGeneral import *
import copy

# n and m are passed in

# generate m samples each of n normal distributions
# means and std dev for each can be generated by another distribution

def getData(n, m):
    values, distances, means, std_devs, probs = generateMatrix(n, m)

    #store a copy of values, distances
    original_values = copy.deepcopy(values)
    original_distances = copy.deepcopy(distances)
    original_probs = copy.deepcopy(probs)

    #assume that we are going to remove n/2 scenarios for now
    probs,distances,values,removed = eliminate_K(probs,distances,n//2,values)
    


#if __name__=="__main__":
